name: hello-world
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs: 
  hello:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!